name: Android CI (build from zip)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure ZIP is present
        run: |
          test -f SalesMaster_FullMulti_v1.zip || (echo "ZIP not found in repo root" && exit 1)
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Set up Gradle 8.2 (no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2
          cache-disabled: true

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          rm -rf project
          unzip -q SalesMaster_FullMulti_v1.zip -d project
          ls -la project

      - name: Build Debug APK
        working-directory: project
        run: gradle :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: project/app/build/outputs/apk/debug/*.apk
